"""added code column to departments

Revision ID: 2
Revises: 1
Create Date: 2026-09-15 16:57:50.807101

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2'
down_revision: str | Sequence[str] | None = '1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint('uq_department_code', 'departments', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_department_code', 'departments', type_='unique')
    op.drop_column('departments', 'code')
    # ### end Alembic commands ###
